# Plotting of intermediate results. Plots for report were made using results/plot.py and results/generate_results.py.
# These functions are mostly for debugging and hyper parameter tuning during training
# Some of the plotting functions were generated by ChatGPT
# OpenAI, ChatGPT, June 23, 2025

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as ptchs
from matplotlib.patches import Polygon

def plot_traj(traj, success_tracker, file_name, start, goals, params, rectangles = None, circles = None, polygons = None, boundary = None):

    dims = traj.shape
    stepps = dims[0]
    nx = dims[1] - 1
    num_traj = dims[2]

    plt.figure()

    # Trajectories
    plt.figure(figsize=(8, 6))
    for i in range(num_traj):
        if success_tracker[i] == 1:
            traj_color = 'green'
            plt.plot(traj[:, 0, i], traj[:, 1, i], linewidth=0.5, label=f'Traj {i+1}', color = traj_color) 

    for i in range(num_traj):
        if success_tracker[i] == 0:
            traj_color = 'red'
            plt.plot(traj[:, 0, i], traj[:, 1, i], linewidth=0.5, label=f'Traj {i+1}', color = traj_color)  

    for i in range(num_traj):
        if success_tracker[i] == -1:
            traj_color = 'black'
            plt.plot(traj[:, 0, i], traj[:, 1, i], linewidth=0.5, label=f'Traj {i+1}', color = traj_color)  
            
        # elif success_tracker[i] == 0: 
        #     traj_color = 'red'

        # elif success_tracker[i] == -1:
        #     traj_color = 'black'

                   

    ax = plt.gca()

    # State space boundary
    if np.any(boundary) != None:
        width, height = boundary
        border = ptchs.Rectangle((0, 0), width, height,
                                    linewidth=2, edgecolor='black', facecolor='none', linestyle='--')
        ax.add_patch(border)

        width, height = boundary
        ax.set_xlim(-1, width+1)
        ax.set_ylim(-1, height+1)
        ax.set_aspect('equal', adjustable='box')  # ensure exact scaling
        ax.set_position([0.1, 0.1, 0.8, 0.8])  # use more of the figure space
        ax.set_xlim(left=0, right=width)
        ax.set_ylim(bottom=0, top=height)

    # Rectangular obstacles
    if rectangles != None:
        for rect in rectangles:
            obstacle = ptchs.Rectangle((rect[0], rect[1]), rect[2], rect[3], 
                                linewidth = 1, edgecolor = 'black', facecolor = 'black', alpha = 0.75)
            ax.add_patch(obstacle)

    # Circular obstacles
    if circles != None:
        for circ in circles:
            obstacle = ptchs.Circle((circ[0], circ[1]), circ[2], 
                                    linewidth = 1, edgecolor = 'black', facecolor = 'black', alpha = 0.75)
            ax.add_patch(obstacle)

    if polygons is not None:
        for poly in polygons:
            poly = np.asarray(poly)
            obstacle = ptchs.Polygon(poly, closed=True,
                                     linewidth=1,
                                     edgecolor='black',
                                     facecolor='black',
                                     alpha=0.75)
            ax.add_patch(obstacle)

    # Initial state
    plt.scatter(start[0], start[1], color='blue', s=100, label="Start")

    for goal in goals:
        if len(goal) == 2 and isinstance(goal[0], int):
            plt.scatter(goal[0], goal[1], color='blue', s=100, label="Goal")
        elif len(goal) == 3:
            rect_goal_set = ptchs.Rectangle(goal[0], goal[1], goal[2], linewidth = 1, edgecolor = 'black', facecolor = 'blue')
            ax.add_patch(rect_goal_set)
    

    # Formatting
    plt.xlabel('x_1')
    plt.ylabel('x_2')
    plt.title(f'Trajectories with sucess rate of {params[0]*100:.2f}% and lambda = {params[1]}')
    plt.grid()
    plt.axis("equal")
    # plt.show()

    plt.savefig(file_name + ".png")

def plot_point_cloud(points_2xn):
    """
    Plots a 2×N point cloud using matplotlib.

    Parameters:
    points_2xn (np.ndarray): A 2×N numpy array where each column is a point [x, y].

    Raises:
    ValueError: If the input is not a 2×N numpy array.
    """
    if not isinstance(points_2xn, np.ndarray) or points_2xn.shape[0] != 2:
        raise ValueError("Input must be a 2×N numpy array.")

    x = points_2xn[0, :]
    y = points_2xn[1, :]

    plt.figure()

    plt.figure(figsize=(6, 6))
    plt.scatter(x, y, c='blue', s=10)
    plt.xlabel("X")
    plt.ylabel("Y")
    plt.title("2D Point Cloud")
    plt.axis('equal')
    plt.grid(True)

def plot_costs(data, success_tracker, params, file_name):

    costs = np.zeros(int(np.sum(success_tracker)))

    i = 0
    for j, datum in enumerate(data):
        if success_tracker[j]:
            costs[i] = datum
            i += 1
    
    plt.figure()

    plt.hist(-costs, bins=20, edgecolor = 'black')
    plt.title(f"Cost of safe trajectories with sucess rate of {params[0]*100:.2f}% and lambda = {params[1]} \n Average cost = {np.mean(costs)}")
    # plt.xlim(0,0)
    plt.xlabel("Cost")
    plt.ylabel("Frequency")
    plt.grid(True)

    plt.savefig(file_name + "_costs.png")

def plot_polygons(polygons, show_vertices=False):
    """
    polygons: list of ndarrays, each of shape (N,2)
              [[x1,y1], [x2,y2], ..., [xN,yN]]
    """

    fig, ax = plt.subplots()

    for poly in polygons:
        poly = np.asarray(poly)

        patch = Polygon(poly, closed=True, fill=False)
        ax.add_patch(patch)

        if show_vertices:
            ax.scatter(poly[:, 0], poly[:, 1])

    ax.set_aspect('equal')
    ax.autoscale()
    plt.show()
